### ISSUE TITLE
Create templates for better maintaining

### ISSUE THREAD

**Issue by Dun-sin** [aditya-singh9/ExpressJS-Snippets#2]
I saw this project is open to contributions, and it doesn't have Pull request and issue templates, it makes for you to maintain your projects.

Here are links for reference: 
[Pull Request Template](https://learn.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops)
[Pull Request and Issue Template](https://bakingclouds.com/multiple-template-choices/)

**Comment by aditya-singh9** [comment]
Do you want to create those templates?

**Comment by Dun-sin** [comment]
> Do you want to create those templates?

I think I'm good with one issue to work with, let's give someone else a chance

also, you need to add the `hacktoberfest` label to this issue and `hacktoberfest-accepted` to pull requests accepted (they only count in October, so you need to wait till then to merge them)

**Comment by FireNdIce3** [comment]
Hi there! Can I work on this?

**Comment by FireNdIce3** [comment]
@aditya-singh9 
I have created the templates and opened a PR. Can you please look into it
My PR is #8 
Thanks
